baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'UNESCO Klub Petefi'
theme = 'lugo'

[params.author]
  name = "Mila Dragic"
  email = "example@text.here"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
